id: A0A7355DA
title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa Lhundrupma)
  from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
type: translation
pechas:
- I038F348B
- IA0401F19
- I17CBC8A3
- I9DE49982
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:00.901763
  last_modified_at: 2023-01-04 11:33:00.901775
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I038F348B/4389: B161
  IA0401F19/18A8: B161
  I17CBC8A3/84B9: B161
  I9DE49982/CCFA: B161
